alias ls='lsd --color=auto'
alias grep='grep --color=auto'
alias cat='bat'
alias ncmpcpp='ncmpcpp -b ~/.config/ncmpcpp/bindings'
alias onefetch='onefetch --disabled-fields churn lines-of-code license contributors --ascii-input "$(cat ~/documents/gambling_ascii.txt)"'
alias eww='$HOME/programs/eww/target/release/eww'
alias patchy='git apply --reject --whitespace=fix'
alias commit='$HOME/code/scripts/commit.sh'
alias notify='$HOME/code/scripts/notify.sh'
alias monitor='$HOME/code/scripts/toggleMonitor.sh'
