#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if [[ $(xrandr -q | grep "DP-1 connected") ]]; then
  xrandr --auto
  $HOME/.screenlayout/default.sh
  bspc monitor DP-1 -d I
  bspc monitor eDP-1 -d II III IV V VI VII VIII IX X
else
  xrandr --output DP-1 --off 
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width        10 
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color \#d3b48c
bspc config active_border_color \#8caad2

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

$HOME/code/scripts/autostart.sh

export STARTUP='true'

